In [1]:
import tensorflow as tf

In [4]:
# 0阶张量
mammal =tf.Variable("Elephant", tf.string) ## variable 需要两个参数  输入数据 和输入类型
ignition = tf.Variable(451,tf.int16)
floating = tf.Variable(3.12159265359, tf.float64)
its_complicated = tf.Variable(12.3 -4.85j,tf.complex64)
# variable是特殊的张量，经过处理

In [3]:
[mammal, ignition, floating, its_complicated]

[<tf.Variable 'Variable:0' shape=() dtype=string_ref>,
 <tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>,
 <tf.Variable 'Variable_2:0' shape=() dtype=float32_ref>,
 <tf.Variable 'Variable_3:0' shape=() dtype=complex128_ref>]

In [ ]:
tf.rank()# 可以表示张量的阶数??????秩

### 变量variable

In [3]:
# 创建变量 ---变量是不会被轻易回收的

# 均值为100 标准差0.35的正态分布
W = tf.Variable(initial_value = tf.random_normal(shape=(1,4),mean=100, stddev=0.35), name='W')
b = tf.Variable(tf.zeros([4]),name="b")

In [4]:
[W,b]

[<tf.Variable 'W:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'b:0' shape=(4,) dtype=float32_ref>]

In [5]:
#初始化变量
# 创建会话
sess = tf.Session()
# 把w b 初始化为全局变量

sess.run(tf.global_variables_initializer())
# 执行操作 获取变量值
sess.run([W,b])

[array([[100.24543 ,  99.89038 , 100.322395, 100.39918 ]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [9]:
# 执行更新操作b
sess.run(tf.assign_add(b,[1,1,1,1]))  # 对b进行加操作

array([3., 3., 3., 3.], dtype=float32)

In [10]:
sess.run(b)

array([3., 3., 3., 3.], dtype=float32)

### saver使用

In [ ]:
v1 = tf.Variable(...,name='v1')
v2 = tf.Variable(...,name='v2')

#指定需要保存和恢复的变量
saver = tf.train.Saver({'v1':v1,'v2':v2})  # 把v1和v2两个变量名保存在文件中
saver = tf.train.Saver([v1,v2]) #和上一个不一样 保存的是上边两个操作的名称（name属性的名字）
saver = tf.train.Saver({v.op.name:v for v in [v1,v2]})# 同上
# 执行保存操作
tf.train.saver.save(sess,'my-model',global_step=0)# 1:会话 2：文件名 3：指明当前的步数  ===》filename：'my-model-0'

In [ ]:
# 创建saver
saver = tf.train.Saver({'W':W,'b':b})
# 存储变量到文件
saver.saver(sess,'./summary/test.ckpt',global_step=0)

In [ ]:
# 再次执行更新边变量的操作
sess.run(tf.assign_add(b,[1,1,1,1]))  # 对b进行加操作

# 获取变量b的最新值
sess.run(b)

In [ ]:
# 从文件中恢复变量b
saver.restore(sess,'./summary/test.ckpt-0')
# 查看变量b 是否恢复成功
sess.run(b)

In [ ]:
# 从文件中恢复数据流图的结构
# tf.train.import_meta_graph

### 操作
 操作是一个节点，tf使用数据流图表示算法模型，数据流图由节点和有向边组成，每个节点对应一个操作，因此操作是模型的载体
 
 数据流图有3种不同的节点
 1：存储节点：有状态的变量操作，
 2：计算节点：负责算法的逻辑表达或流程控制
 3：数据节点：数据的占位符操作，用于描述图外输入数据的属性
 #### 操作的输入和输出是张量或操作（函数式变成）


In [ ]:
# 常量操作----目前这两个变量其实没有获得这个值
a = tf.constant(2)
b = tf.constant(3)

In [ ]:
# 只有在创建会话，并且执行会话的时候才会获得值
with tf.Session() as sess:
    print("a: %i" % sess.run(a))
    print("b: %i" % sess.run(b))

In [2]:
# 占位符操作
x = tf.placeholder(tf.int16,shape=(),name="x")
y = tf.placeholder(tf.int16,shape=(),name="y")

In [3]:
# 定义计算操作
add = tf.add(x, y)
mul = tf.multiply(x, y)


In [5]:
# 加载默认数据流图
with tf.Session() as sess:
    # 要先填充数据才能操作
    print("------: %i " % sess.run(add, feed_dict={x:2,y:3}))
    print("------: %i " % sess.run(mul, feed_dict={x:2,y:3}))

------: 5 
------: 6 


### 会话 session
会话提供了估算张量和执行操作的运行环境，他是发放计算任务的客户端，所有计算任务都由他连接的执行引擎完成
tf.session(target=,graph=,config=..) target会话连接的执行引擎，会话加载的数据流图   会话的配置项

In [8]:
# 创建爱你数据流图 y=w*x+b  其中w和b为存储节点，x为数据节点
x = tf.placeholder(tf.float32)
W = tf.Variable(1.0)
b = tf.Variable(1.0)
y = W * x + b
with tf.Session() as sess:
    tf.global_variables_initializer().run() # 全局化数据  给wb赋值----执行操作
    fetch = y.eval(feed_dict={x:3.0})  # 估算张量
    print(fetch)

4.0


In [ ]:
# operation.run 和tensor.eval方法也是会话执行的方法，这两个方法都会调用执行sess.run

####  可以指定节点放置的设备

In [ ]:
with tf.device("/cpu:0"):
    v = tf.Variable(--)

### 优化器 optimizer