In [2]:
import tensorflow as tf

In [4]:
# 0阶张量
mammal =tf.Variable("Elephant", tf.string) ## variable 需要两个参数  输入数据 和输入类型
ignition = tf.Variable(451,tf.int16)
floating = tf.Variable(3.12159265359, tf.float64)
its_complicated = tf.Variable(12.3 -4.85j,tf.complex64)
# variable是特殊的张量，经过处理

In [3]:
[mammal, ignition, floating, its_complicated]

[<tf.Variable 'Variable:0' shape=() dtype=string_ref>,
 <tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>,
 <tf.Variable 'Variable_2:0' shape=() dtype=float32_ref>,
 <tf.Variable 'Variable_3:0' shape=() dtype=complex128_ref>]

In [ ]:
tf.rank()# 可以表示张量的阶数??????秩

### 变量variable

In [3]:
# 创建变量 ---变量是不会被轻易回收的

# 均值为100 标准差0.35的正态分布
W = tf.Variable(initial_value = tf.random_normal(shape=(1,4),mean=100, stddev=0.35), name='W')
b = tf.Variable(tf.zeros([4]),name="b")

In [4]:
[W,b]

[<tf.Variable 'W:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'b:0' shape=(4,) dtype=float32_ref>]

In [5]:
#初始化变量
# 创建会话
sess = tf.Session()
# 把w b 初始化为全局变量

sess.run(tf.global_variables_initializer())
# 执行操作 获取变量值
sess.run([W,b])

[array([[100.24543 ,  99.89038 , 100.322395, 100.39918 ]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [9]:
# 执行更新操作b
sess.run(tf.assign_add(b,[1,1,1,1]))  # 对b进行加操作

array([3., 3., 3., 3.], dtype=float32)

In [10]:
sess.run(b)

array([3., 3., 3., 3.], dtype=float32)

### saver使用

In [ ]:
v1 = tf.Variable(...,name='v1')
v2 = tf.Variable(...,name='v2')

#指定需要保存和恢复的变量
saver = tf.train.Saver({'v1':v1,'v2':v2})  # 把v1和v2两个变量名保存在文件中
saver = tf.train.Saver([v1,v2]) #和上一个不一样 保存的是上边两个操作的名称（name属性的名字）
saver = tf.train.Saver({v.op.name:v for v in [v1,v2]})# 同上
# 执行保存操作
tf.train.saver.save(sess,'my-model',global_step=0)# 1:会话 2：文件名 3：指明当前的步数  ===》filename：'my-model-0'